# Generated by Django 5.2.2 on 2025-07-06 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('type_question', models.CharField(choices=[('multiple', 'Choix multiple'), ('open', 'Question ouverte'), ('wordcloud', 'Nuage de mots'), ('matching', 'Correspondance'), ('fill_blanks', 'Remplir les blancs')], default='multiple', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('16_24', '16-24 ans'), ('25_30', '25-30 ans'), ('31_36', '31-36 ans'), ('plus_36', 'Plus de 36 ans')], default='16_24', max_length=10)),
                ('experience', models.CharField(choices=[('moins_1', 'Moins de 1 an'), ('1_3', '1 à 3 ans'), ('3_5', '3 à 5 ans'), ('plus_5', 'Plus de 5 ans')], default='moins_1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sondagepro.profileposte')),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('matching_pair', models.CharField(blank=True, max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='sondagepro.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('postes_cibles', models.ManyToManyField(blank=True, related_name='questionnaires', to='sondagepro.profileposte')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='sondagepro.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sondagepro.theme'),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sondagepro.choix')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sondagepro.question')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'question')},
            },
        ),
    ]
