# Generated by Django 5.2.2 on 2026-06-14 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondagepro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reponse',
            name='pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, choices=[('moins_1', 'Moins de 1 an'), ('1_3', '1 à 3 ans'), ('3_5', '3 à 5 ans'), ('plus_5', 'Plus de 5 ans')], default='moins_1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tranche_age',
            field=models.CharField(blank=True, choices=[('16_24', '16-24 ans'), ('25_30', '25-30 ans'), ('31_36', '31-36 ans'), ('plus_36', 'Plus de 36 ans')], default='16_24', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
