# Generated by Django 5.2.2 on 2026-06-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondagepro', '0002_alter_reponse_unique_together_questionnaire_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='temps_limite',
            field=models.PositiveIntegerField(default=0, help_text='Temps en secondes (0 = sans limite)'),
        ),
    ]
