# Generated by Django 5.2.2 on 2025-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondagepro', '0002_rename_profileposte_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='autoriser_autre',
            field=models.BooleanField(default=False),
        ),
    ]
